#!/bin/bash

numeros=0
strings=0

while read linha; do

    if [ $linha -eq $linha ] 2> /dev/null ; then
        ((numeros+=1))
        continue
    fi
    ((strings+=1))

done <arq.txt

echo "Total: $strings strings e $numeros números"
