#!/bin/bash

read -p "Digite o número a ser validado: " numero

if (echo $numero | grep -E '^R\$ ([0-9]{1,3}(\.[0-9]{3})*|[0-9]+)(\,[0-9]{2})?$'); then
    echo "O número está no padrão brasileiro"
else
    echo "O número não está no padrão brasileiro"
fi
